stats: STATSAPI
mysql:
   host: 127.0.0.1
   port: 3306
   user: bedwarsunlimited
   database: bedwarsunlimited
   password: password
gameworld: bw_gameworld
presetworld: presets
creature_spawn: false
group_command: true
leave_command: true
tab_header_and_footer: true
default_group_size: 2
group_size_permission:
  - "bw.group.4->4"
  - "bw.group.8->8"
  - "bw.group.*->*"
physics:
   crop-trampeling: false
   game:
      water-update: false
      other: true
   presets:
      water-update: true
      other: true
   world:
      water-update: false
      other: false
worlds:
   allow_rain: false
   default_time: 1000
   presets_time: 1000
   game_time: 1000
generator:
   splitted:
      blocks: 500
      every: 40
gameplacement:
   gap: 500
   y-position: 70
   z-position: 500
game:
   leaveitem_slot: 8
   teamselector_slot: 0
   spectator_out_fly: 50
   no_drop:
     - WEB
     - GLOWSTONE
     - TNT
   special_items:
      TNT:
         item: TNT
      Teleporter:
         item: FIREWORK
      TeamChest:
         block: ENDER_CHEST
      RescuePlatform:
         item: NETHER_STAR
         set: STAINED_GLASS
         teamcolor: true
         radius: 2
lobby:
   respawn_y: 40
   challenger:
      enabled: true
      slot: 0
      cooldown: 3
   gamelist:
      enabled: true
      slot: 1
   leave:
      enabled: true
      slot: 8
      server: Lobby-1
   group:
      enabled: true
      slot: 7
challenger:
   lobby_time: 5
defaultsettings:
   fixed_teams: false
   allow_join: true
   allow_spectate: true
   tnt_auto_ignite: true
   tnt_detroy_map: false
   lobby_leave: NORMAL
   min_players: 2
   max_players: 0
   min_lobby_countdown: 10
   game_end: 36000
   ending_countdown: 10   
   spawn_protection: 1
points:
   lost: 10
   won: 50
   kill: 10
   bed: 20
death_y_offset: 20
death_timeout: 80